version: '3.8'

services:
  mysql-usuarios:
    image: mysql:8.0
    container_name: mysql-ms-usuarios
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grupo_cordillera
    ports:
      - "3306:3306"
    volumes:
      - mysql_usuarios_data:/var/lib/mysql

volumes:
  mysql_usuarios_data: